server:
  port: 8099
  servlet:
    context-path: /chd
    session:
      cookie:
        max-age: 60000s
      timeout: 1800s

  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 10
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 1000
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 2048
    # 是否分配的直接内存
    direct-buffers: true

    accesslog:
      dir: /home/undertow/
      enabled: true
      prefix: undertown.access_log.
      suffix: log


spring:
  session:
    ## store-type redis     -----redis缓存session，
    #  store-type: none     -----表示不用缓存sesion数据信息
    store-type: none
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.27.193.222:23306/chd_check?useSSL=false&serverTimezone=UTC
    username: root
    password: Gongfu@123456
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 3
    minIdle: 2
    maxActive: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 1800000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  redis:
    ##redis 单机环境配置
    host: 127.0.0.1
    port: 9001




ejet-comm-web:
  ### ===========================  token认证设置   ===============================
  openTokenAuth: true
  openSessionAuth: false
  authTimeout: 18000
  authIgnoreURLs: /chd/auth/login,/auth/logout

  ### ===========================  上传文件路径设置   ===============================
  # 存储物理路径
  storagePhysicalPath: /home/upload
  ## 访问相对路径（外部程序）
  relativeURL: /
  # 是否分类存储(image: 图片 video: 视频 audio: 音频 html: 网页 file:其他所有)
  storageType: false
  #  存储按天日期
  storageByDate: false
  # 是否更改文件名称(适用唯一)
  changeFilename: true


# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

